version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: taskflow-postgres
    restart: always
    environment:
      POSTGRES_USER: taskflow_user
      POSTGRES_PASSWORD: taskflow_pass
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
