apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: default
data:
  APP_ENV: "production"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "30"
  DATABASE_URL: "postgresql+asyncpg://taskflow_user:taskflow_pass@taskflow-postgres-service:5432/taskflow"
  SYNC_DATABASE_URL: "postgresql://taskflow_user:taskflow_pass@taskflow-postgres-service:5432/taskflow"
